version: "3.7"

services:
  ant:
    build: ./ant
    command: ["bm", "nn"]
    volumes:
      - ./ant:/ant
      - ../data:/data
      - ../docs:/docs
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ../data:/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"